Activity to user merge attempt
DPITmsg/ConnectWave-BE pull request #22
Opened 2023-10-31 12:15 UTC by TRBF

2023-11-05 09:28 UTC, Ducuvlad requested changes

2023-11-05 09:28 UTC, Ducuvlad commented on backend/controller/activity_to_user_controller.py
> +        created_quit = service.remove_user_from_activity(username=data['username'], activity_id=data['activity_id'])
Created_quit is always None since .remove_user_from_activity() does not return anything.

2023-11-05 09:28 UTC, Ducuvlad commented on backend/services/activity_to_user_service.py
> +        if(get_activity_to_user(username, activity_id)):
If you do not find an activity the result of this get will be None. If(None) is False, but you need it to be true so you can create the ActivityToUser.
Please add a check for None https://bobbyhadz.com/blog/python-check-if-none

2023-11-07 17:59 UTC, TRBF commented
Realised Alex was right, `activity.id` makes much more sense.

2023-11-07 18:05 UTC, Ducuvlad approved these changes

2023-11-07 18:06 UTC, merged